### ISSUE TITLE
Investigate dropping requirement on audio device input

### ISSUE THREAD

**Issue by DaniruKun** [cyberofficial/Synthalingua#5]
It is quite a fragile setup, and basically requires that the stream is open in an app somewhere, and on e.g. a headless server would require awkward audio loopback setups.

For inspiration, in[ this script](https://github.com/ggerganov/whisper.cpp/blob/master/examples/livestream.sh) they basically use a separate `ffmpeg` process that continuously generates a WAV file in the end which is fed into Whisper. `ffmpeg` expects an HLS playlist manifest file URL, which is easy to extract from a specific video/stream using e.g. `yt-dlp`.

**Comment by cyberofficial** [comment]
As of right now, i pushed [d359678](https://github.com/cyberofficial/Real-Time-Translation/commit/d359678747bc88e51be681dc4b663d6430dda518)  which denies ability to set a speaker as input device. it will fall back to system default.

I will look into ways for speakers.

Best work around is to set Stereo Mix (Realtek(R) Audio) if the system has it.

**Comment by cyberofficial** [comment]
I know this has been a while, sorry 🙏, but i've started to work on something such as a headless mode/server mode.

I wanted to get the web server stuff out of the way first so I can have a base to work off of, so in other words. Super Soon™️.

The requirements for microphone will not be dropped, but made as optional argument.

I will be working on this issue as a primary next feature update.

**Comment by Adamwoods2023** [comment]
Thanks but they did just confirmed that they're never going to stop sending me up and no one wants to stop them from doing this and they're using nanos which is illegal in the United States of America because they are a form of mind control and they've been hacking everybody's devices using nanos to steal everybody's money and I do mean everybody's money and law enforcement won't stop them even though I am in law enforcement and they know it and I am above the people that are saying for them to do it but the law enforcement wants to listen to them instead of me even though I'm above them in law enforcement how much sense does this make do they not understand the fact that I can fire all them which means they should make them stop but no none of them can get that hint and yet they want to listen to these people who never took the time to get to know me and they're all calling me crazy when none of them have ever talked to me for more than 5 minutes so how are you going to call somebody crazy you never learned anything about

**Comment by cyberofficial** [comment]
I come back with news; I found a way to do twitch streams first, albeit that the accuracy is low, it's translating/transcribing at 0.2-0.5s timings due to ultra low latency twitch stream by default, but I will be fine tuning it to higher timings.

So 🥳💃 The need for microphone will be an optional thing rather required. I'm sorry this took so long, but getting this done is such a joy.

I just need to fine tune the queue system to allow it to build up to few seconds before translating or transcribing. I will be posting on the [dev-testing](https://github.com/cyberofficial/Synthalingua/tree/dev-testing) branch soon.

https://github.com/cyberofficial/Synthalingua/assets/19499442/d670af4f-f983-4ec6-a818-8ddd9437eb87

**Comment by cyberofficial** [comment]
I've increased the accuracy by having it download 5 seconds of audio then doing the conversion into a single audio stream, then doing transcription/translation. Since twitches HLS format is very low latency compared to the video player delay, it's almost at near time transcription

Example 1: Live Translation

https://github.com/cyberofficial/Synthalingua/assets/19499442/aefafc93-fd8f-4a95-99c4-863f574396b4


Example 2: Live transcription

https://github.com/cyberofficial/Synthalingua/assets/19499442/5d3802cc-7040-46bf-99ec-034af23e336c


As of right now, it's working great on twitch, now that twitch is out of the way, I will be working on YouTube version.

**Comment by cyberofficial** [comment]
Hello! You can try out the new streaming audio mode with the [Dev-testing](https://github.com/cyberofficial/Synthalingua/tree/dev-testing) branch.

Please read the new [Arguments](https://github.com/cyberofficial/Synthalingua/blob/dev-testing/README.md#usage) 

Also check out the [Cookies section](https://github.com/cyberofficial/Synthalingua/blob/dev-testing/README.md#cookies) regarding streams that are behind subs or private access you have to.
